version: "3.7"

services:

  app:
    depends_on:
      - mongodb
    restart: unless-stopped
    image: rizaladitiya/item-app:v1
    command: sh -c "npm install && npm start"
    ports:
      - 80:8080
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
    stdin_open: true
    tty: true
      
  mongodb:
    restart: unless-stopped
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - app-db:/data/db
volumes:
  app-db:
    
