version: "3.7"

services:

  item-app:
    depends_on:
      - item-db
    #restart policy
    restart: unless-stopped
    #image docker hub
    image: rizaladitiya/item-app:v1
    working_dir: /app
    volumes:
      - ./app:/app
    #jalankan node
    command: sh -c "npm install && npm start"
    #port mapping 80
    ports:
      - 80:8080
    environment:
      - DB_HOST=item-db
      - DB_PORT=27017
    stdin_open: true
    tty: true
      
  item-db:
    restart: unless-stopped
    #gunakan image mongo:3
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - app-db:/data/db
#pakai volume app-db
volumes:
  app-db:
