# API Version
apiVersion: v1
# Kubernetes resource
kind: ConfigMap
# ConfigMap metadata resource
metadata:
  name: mongo-configmap
data:
  # Mongodb storage configuration sets the dbpath to "/data/db"
  mongo.conf: |
    storage:
      dbpath: /data/db
